name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
      - uses:actions/checkout@v3
      - name:Run a one-line script
        run:echo Hello, world!
      - name:Run a multi-line script
        run:|
          echo Add other actions to build,
          echo test, and deploy your project.
          
 name: Cache
  uses: actions/cache@v3.0.8
  with:
    path: 
    key: 
    restore-keys: 
    upload-chunk-size: 
